name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.23'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxkbfile-dev dpkg-dev fakeroot

    - name: Verify CMake version
      run: cmake --version

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: List build directory contents after build
      run: ls -la build

    - name: Package project
      run: |
        cd build
        cpack -G DEB
        ls -la

    - name: Find generated .deb file
      id: find_deb
      run: echo "::set-output name=deb_path::$(find build -name '*.deb')"

    - name: Upload Debian package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: xkb-switch-deb
        path: ${{ steps.find_deb.outputs.deb_path }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v1.0.${{ github.run_number }}"  # Example of using a pseudo semantic versioning
        release_name: "Development Build 1.0.${{ github.run_number }}"
        draft: false  # Ensure the release is published
        prerelease: false  # Change to false if you do not want it as a prerelease

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.find_deb.outputs.deb_path }}
        asset_name: xkb-switch-1.0.${{ github.run_number }}.deb
        asset_content_type: application/octet-stream

